### ISSUE TITLE
Uncaught (in promise) Error: Could not identify object

### ISSUE THREAD

**Issue by ptpaterson** [ptpaterson/netlify-faunadb-graphql-auth#12]
Update functions are not working correctly, but add and delete are fine.

**Comment by ptpaterson** [comment]
Thanks @ctjewlis for pushing me to figure this out.  Not back to the functionality that I want, but will bring it back later.

**Comment by ctjlewis** [comment]
No worries at all @ptpaterson. I actually started refactoring parts of this to TS, with the eventual goal of having `type-graphql` decorated classes compile to schemas, but after a lot of webpack tinkering and some package.json refactoring, the login process is breaking in a way that isn't super obvious.

The login action finally returns `login: true`, but something goes wrong at the cookie stage I think, with the header, but I'm not sure what. It was working before the TS refactor. I could use any tips or thoughts, plus you might get some inspiration from the grunt work I did regarding the project structure (`"dev": "npx npm-run-all -p watch:src watch:functions"` etc.)

https://github.com/ctjlewis/netlify-faunadb-graphql-auth/tree/typescript

**Comment by ptpaterson** [comment]
Couple of points with these lines:

https://github.com/ptpaterson/netlify-faunadb-graphql-auth/blob/7408734fb1fb019693f26d1e61b869e0d0f897f1/functions/graphql/overrideSchema.js#L13-L15

1. The resolver directive doesn't do anything, this is outside of Fauna.
2. The overridden `login` resolver returns a boolean, not a string.

The override schema mutation should be: 

    login(data: LoginInput): Boolean!

I am surprised this didn't cause bigger issues.  Maybe it can but I haven't see the cases yet.

Is it possible that transpilation converted it to something that _would_ cause more apparent problems?  Enough to interrupt page routing?

**Comment by ctjlewis** [comment]
Totally possible, it's transpiling to ES2018 with Webpack, there could be something funky in there that elevates the impact of the error.

**Comment by ctjlewis** [comment]
I made that change - it doesn't actually help us out here, as weirdly, `login` would tend to return Boolean anyway (????), and so we see the same output: bad login info yields `login: false`, good login yields `login: true`, but the cookies no longer set, so you get `unauthorized` because there's no secret in the header.

**Comment by ptpaterson** [comment]
ah, but it returns the boolean casted to a string!  
![image](https://user-images.githubusercontent.com/7998974/105764687-49b59e00-5f25-11eb-87e6-26b684ee0dd6.png)

**Comment by ctjlewis** [comment]
See! This is why I needed your help! Making progress already.

**Comment by ptpaterson** [comment]
I also just saw a strange phenomenon in GraphiQL where if I enter a bad password immediately following a good one, it returns true (or "true").  not until I provide a bad email does it reset.  So login is checking if it's a good cookie key and disregarding the password.
